---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ctx.namespace}}
  name: {{app_name_git}}
spec:
  serviceName: "{{app_name_git}}"
  replicas: 1
  selector:
    matchLabels:
      app: {{app_name_git}}
  template:
    metadata:
      labels:
        app: {{app_name_git}}
    spec:
      containers:
      - image: {{gitea_image}}
        name: {{app_name_git}}
        livenessProbe:
          httpGet:
            path: /
            port: {{gitea.gitea_port1}}
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: {{gitea.gitea_port1}}
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        envFrom:
        - configMapRef:
            name: configmap-{{app_name_git}}
        ports:
        - containerPort: {{gitea.gitea_port1}}
        - containerPort: {{gitea.gitea_port2}}
          protocol: TCP
        volumeMounts:
        - mountPath: "/test"
          name: {{app_name_pos}}-volume
        - mountPath: "./data/gitea/conf"
          readOnly: true
          name: appini-volume
      volumes:
      - name: {{app_name_pos}}-volume
        {% if enable_persistent %}
        persistentVolumeClaim:
          claimName: {{app_name_pos}}-task-claim
        {% else %}
        emptyDir: {}
        {% endif %}
      - name: {{app_name_git}}-config
        configMap:
          name: configmap-{{app_name_git}}
      - name: appini-volume
        configMap:
          name: appini