---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea-service-ingress
  namespace: {{ctx.namespace}}
spec:
  rules:
  - host: {{host}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitea
            port:
              number: {{gitea.gitea_port1}}
