---
apiVersion: v1
kind: Service
metadata:
  name: {{app_name_git}}
  namespace: {{ctx.namespace}}
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: {{gitea.gitea_port1}}
    targetPort: {{gitea.gitea_port1}}
  selector:
    app: {{app_name_git}}
