---
ctx:
  namespace: gitea

global:
  enable_persistent: true
  host: example.com
  postgres_image: "postgres:9.6"
  gitea_image: "gitea/gitea:1.13.1"
  gitea_data: gitea
  gitea:
    gitea_port1: 3000
    gitea_port2: 222
  postgres:
    postgres_port: 5432
    postgres_host: "postgres"
  pv:
    storage: 1Gi
#import:
#- versions.yaml
#- vars/test/

include:

#----------------------------------------------------------------------------
# gitea common

- name: gitea_manifests
  include:
  - name: namespace
  - name: pv
  - name: configmap
  - name: postgres
  - name: gitea


