---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-postgres
data:
  POSTGRES_USER: gitea
  POSTGRES_PASSWORD: gitea
  POSTGRES_DB: gitea



---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-gitea
data:
  USER_UID: "1000"
  USER_GID: "1000"
  DB_TYPE: postgres
  DB_HOST: 172-17-0-5.default.pod.cluster.local:5432
  DB_NAME: gitea
  DB_USER: gitea
  DB_PASSWD: gitea