---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-postgres
data:
  POSTGRES_USER: gitea
  POSTGRES_PASSWORD: gitea
  POSTGRES_DB: gitea
  USER_UID: "1000"
  USER_GID: "1000"
  DB_TYPE: postgres
  DB_HOST: postgres-service:5432
  DB_NAME: gitea
  DB_USER: gitea
  DB_PASSWD: gitea
