---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: gitea
  namespace: gitea
spec:
  serviceName: "gitea"
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: postgres-task-claim
        - name: gitea-config
          configMap:
            name: configmap-gitea    
      containers:
        - image: gitea/gitea:1.13.1
          name: gitea
          ports:
            - containerPort: 3000
            - containerPort: 222
              protocol: TCP
          volumeMounts:
            - mountPath: "/test"
              name: postgres-volume