---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  replicas: 1
  serviceName: "postgres"
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:

      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: postgres-task-claim
      containers:
        - image: postgres:9.6
          name: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: gitea
            - name: POSTGRES_PASSWORD
              value: gitea
            - name: POSTGRES_DB
              value: gitea
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-volume