---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: gitea 
  name: postgres-pv-volume
  labels:
    type: gitea
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/test"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gitea 
  name: postgres-task-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
