---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ctx.namespace}}
  name: {{app_name_pos}}-pv-volume
  labels:
    app: {{app_name_git}}
spec:
  storageClassName: manual
  capacity:
    storage: {{pv.storage}}
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/test"

