---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ctx.namespace}}
  name: postgres-pv-volume
  labels:
    type: gitea
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/test"

