---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ctx.namespace}}
  name: postgres-pv-volume
  labels:
    type: gitea
spec:
  storageClassName: manual
  capacity:
    storage: {{pv.storage}}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{gitea.gitea_mountPath}}

