---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ctx.namespace}}
  name: {{app_name_pos}}-task-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{pv.storage}}