apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ctx.namespace}}
  name: postgres-task-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{pv.storage}}
