---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ctx.namespace}}
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      namespace: {{ctx.namespace}}
      labels:
        app: postgres
    spec:
      containers:
      - image: {{postgres_image}}
        name: postgres
        envFrom:
        - configMapRef:
            name: configmap-postgres
        ports:
        - containerPort: {{postgres.postgres_port}}
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-volume
      volumes:
      - name: postgres-volume
        persistentVolumeClaim:
          claimName: postgres-task-claim
