---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ctx.namespace}}
  name: {{app_name_pos}}
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: {{postgres.postgres_port}}
    targetPort: {{postgres.postgres_port}}
  selector:
    app: {{app_name_pos}}
