---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ctx.namespace}}
  name: appini
data:
  app.ini: |
    APP_NAME = Gitea
    RUN_MODE = prod
    RUN_USER = git

    [repository]
    ROOT = /data/git/repositories

    [repository.local]
    LOCAL_COPY_PATH = /data/gitea/tmp/local-repo

    [repository.upload]
    TEMP_PATH = /data/gitea/uploads

    [server]
    APP_DATA_PATH    = /data/gitea
    DOMAIN           = {{host}}
    SSH_DOMAIN       = {{host}}
    HTTP_PORT        = {{gitea.gitea_port1}}
    ROOT_URL         = http://{{host}}
    DISABLE_SSH      = false
    SSH_PORT         = 22
    SSH_LISTEN_PORT  = 22
    LFS_START_SERVER = true
    LFS_CONTENT_PATH = /data/git/lfs
    LFS_JWT_SECRET   = tzOmUwFrbgAD-B8a3kvwtX7pYq-bUswFr0P6fcs-gkM
    OFFLINE_MODE     = false
    [database]
    PATH     = /data/gitea/gitea.db
    DB_TYPE  = postgres
    HOST     = "{{postgres.postgres_host}}:{{postgres.postgres_port}}"
    NAME     = {{gitea_data}}
    USER     = {{gitea_data}}
    PASSWD   = {{gitea_data}}
    LOG_SQL  = false
    SCHEMA   = ""
    SSL_MODE = disable
    CHARSET  = utf8

    [indexer]
    ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve

    [session]
    PROVIDER_CONFIG = /data/gitea/sessions
    PROVIDER        = file

    [picture]
    AVATAR_UPLOAD_PATH            = /data/gitea/avatars
    REPOSITORY_AVATAR_UPLOAD_PATH = /data/gitea/repo-avatars
    DISABLE_GRAVATAR              = false
    ENABLE_FEDERATED_AVATAR       = true

    [attachment]
    PATH = /data/gitea/attachments

    [log]
    MODE                 = console
    LEVEL                = info
    REDIRECT_MACARON_LOG = true
    MACARON              = console
    ROUTER               = console
    ROOT_PATH            = /data/gitea/log


    [security]
    INSTALL_LOCK   = true
    SECRET_KEY     = 1U5jyTR8CAwQNGBSwXlZaTUfyqBU054t8UQdfajpbBeMtOAL4vQnexYH4HwpKoxg
    INTERNAL_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2MTA4MzM5ODJ9.i9qhPlgP2GwF-MP1FlZzaBWHsmawxurlEsKtIVi-oi8

    [service]
    DISABLE_REGISTRATION              = false
    REQUIRE_SIGNIN_VIEW               = false
    REGISTER_EMAIL_CONFIRM            = false
    ENABLE_NOTIFY_MAIL                = false
    ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
    ENABLE_CAPTCHA                    = false
    DEFAULT_KEEP_EMAIL_PRIVATE        = false
    DEFAULT_ALLOW_CREATE_ORGANIZATION = true
    DEFAULT_ENABLE_TIMETRACKING       = true
    NO_REPLY_ADDRESS                  = noreply.localhost

    [oauth2]
    JWT_SECRET = 5xBvwFePHdI-OVrnX1hjoWGhPFsih5F9eUO3os_7pCE

    [mailer]
    ENABLED = false

    [openid]
    ENABLE_OPENID_SIGNIN = true
    ENABLE_OPENID_SIGNUP = true
