---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ctx.namespace}}
  name: configmap-{{app_name_git}}
data:
  USER_UID: "1000"
  USER_GID: "1000"
  DB_TYPE: postgres
  DB_HOST: "{{postgres.postgres_host}}:{{postgres.postgres_port}}"
  DB_name: {{app_name_git}}
  DB_USER: {{app_name_git}}
  DB_PASSWD: {{app_name_git}}
