---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ctx.namespace}}
  name: configmap-gitea
data:
  USER_UID: "1000"
  USER_GID: "1000"
  DB_TYPE: postgres
  DB_HOST: {{postgres.postgres_host}}:{{postgres.postgres_port}}
  DB_name: {{gitea_data}}
  DB_USER: {{gitea_data}}
  DB_PASSWD: {{gitea_data}}
