---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ctx.namespace}}
  name: configmap-postgres
data:
  POSTGRES_USER: {{gitea_data}}
  POSTGRES_PASSWORD: {{gitea_data}}
  POSTGRES_DB: {{gitea_data}}
