---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ctx.namespace}}
  name: configmap-{{app_name_pos}}
data:
  POSTGRES_USER: {{app_name_git}}
  POSTGRES_PASSWORD: gitea
  POSTGRES_DB: {{app_name_git}}
